# Generated by Django 4.2.1 on 2023-05-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default=2, upload_to='brand/'),
            preserve_default=False,
        ),
    ]
